<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INDP277LT" failures="1" tests="2" name="Test" time="0.032" errors="0" timestamp="2021-01-12T11:44:55 IST">
  <testcase classname="listenerSmoke.Demo_smoke" name="testMethod01_smoke" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at listenerSmoke.Demo_smoke.testMethod01_smoke(Demo_smoke.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testMethod01_smoke -->
  <testcase classname="listenerSmoke.Demo_smoke" name="testMethod02_smoke" time="0.003"/>
</testsuite> <!-- Test -->
